services:
  - type: web
    name: student-results-app
    runtime: docker
    plan: free
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    repo: https://github.com/SrigadaAkshayKumar/student-results-dashboard
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8501
